import 'dotenv/config';

const { PORT,
PG_HOST,
PG_PORT,
PG_USER,
PG_PASSWORD,
PG_DATABASE,
NODE_ENV,
AQ_API_KEY,
AQ_API_ENDPOINT,API_BASE_URL,PARIS_LATITUDE,
PARIS_LONGITUDE} = process.env;

export const ENV = Object.freeze({ PORT,
PG_HOST,
PG_PORT,
PG_USER,
PG_PASSWORD,
PG_DATABASE,
NODE_ENV,
AQ_API_KEY,
AQ_API_ENDPOINT,API_BASE_URL,PARIS_LATITUDE,
PARIS_LONGITUDE } );